genetic_algorithm:
  max_time: 60   # Tiempo máximo por simulación (segundos)
  pop_size: 50   # Tamaño de la población
  genome_length: 10  # Número de coordenadas en el genoma
  mut_prob: 0.2  # Probabilidad de mutación
  cx_prob: 0.7   # Probabilidad de cruce